### ISSUE TITLE
没有自动安装

### ISSUE THREAD

**Issue by Sudors** [songxiaoliang/react-native-app-upgrade#10]
下载是下载了。但下载完成没有自动安装。

**Comment by Sudors** [comment]
android 5.1.1 , api 22

**Comment by Sudors** [comment]
跟踪到具体错误是这个
Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

**Comment by Sudors** [comment]
是安装时候报的错误

**Comment by songxiaoliang** [comment]
@Sudors FLAG_ACTIVITY_NEW_TASK这个标志位存在的，应该不会出现这个问题

**Comment by songxiaoliang** [comment]
@Sudors 我更新了代码，你重新pull下来试下。

**Comment by Sudors** [comment]
可以了谢谢！ 没看到你改什么呀！

**Comment by songxiaoliang** [comment]
@Sudors 你是重新pull的代码吗？pull之前的可以还是pull之后的可以？

**Comment by Sudors** [comment]
pull 之后的可以 我就替换了这个文件

**Comment by songxiaoliang** [comment]
@Sudors 好的，解决了就行了。

**Comment by songxiaoliang** [comment]
@Sudors 加我微信 mir_song， 我拉你进群。有问题直接讨论，这个issue我先关闭了。

**Comment by wangyihang875** [comment]
我也不能自动安装，请问怎么解决的

**Comment by songxiaoliang** [comment]
@wangyihang875 加微信说吧
