### ISSUE TITLE
感谢作者！希望npmjs那边的版本也同步升级为2.0的

### ISSUE THREAD

**Issue by iCodeAnt** [songxiaoliang/react-native-app-upgrade#104]
https://www.npmjs.com/package/rn-app-upgrade
希望这里的也同步升级！万分感谢！
如果没有升级，安装了1.2.0的 改如何升级成github最新的2.0啊？

**Comment by songxiaoliang** [comment]
@iCodeAnt 目前npm上的库还不能进行升级，需要等年后。如果你现在想使用最新的2.0，可以将code download到你的本地，然后替换即可。

**Comment by songxiaoliang** [comment]
@iCodeAnt npm已更新2.0.1版本。
