### ISSUE TITLE
yarn add react-native-app-upgrade下载没有东西啊

### ISSUE THREAD

**Issue by lahala** [songxiaoliang/react-native-app-upgrade#105]
![Xnip2021-02-19_16-23-12](https://user-images.githubusercontent.com/9395580/108477895-cb071300-72ce-11eb-97dc-71476d3f9f5b.jpg)

**Comment by songxiaoliang** [comment]
@lahala 
yarn add rn-app-upgrade
 
  // 低于0.6+版本
  react-native link rn-app-upgrade
