### ISSUE TITLE
有两点问题，还请大佬可以看看

### ISSUE THREAD

**Issue by lahala** [songxiaoliang/react-native-app-upgrade#106]
安卓：
1.下载时经常，进度不到100（基本20左右），就跳到安装界面了哈，有些不友好。
![Xnip2021-02-20_15-38-28](https://user-images.githubusercontent.com/9395580/108588042-19c9b100-7392-11eb-953c-2bfc88d52910.jpg)

2.建议加个下载失败的回调，这样，可以便于我们扩展，让用户去通过其它方式下载apk

**Comment by songxiaoliang** [comment]
@lahala 
第一个问题在2.0.0版本已经fix，npm上还没同步，如果紧急用，可以先使用GitHub上的代码。
2.0.1已经增加下载失败的回调，详细使用请查看READEME文档

**Comment by lahala** [comment]
非常感谢哈！！
