### ISSUE TITLE
TypeError: Cannot read property 'DocumentDir' of undefined

### ISSUE THREAD

**Issue by asagcs** [songxiaoliang/react-native-app-upgrade#107]
”react": "16.13.1",
"react-native": "0.63.4",
"rn-app-upgrade": "^2.1.5"

error: TypeError: Cannot read property 'DocumentDir' of undefined

如果此时我安装rn-fetch-blob，该问题会解决，但是会产生循环依赖的问题。
@songxiaoliang

**Comment by songxiaoliang** [comment]
@asagcs 如果你在本地已经装了rn-fetch-bolb，那么会跟该库产生版本冲突，可以在package.json中使用resolutions来解决。

**Comment by kiddyuchina** [comment]
总结一下使用react-native-app-upgrade遇到的几个问题
1.在 react-native:0.64.0 版本中，rn-fetch-blob 不会自动连接，需要手动连接或安装 rn-fetch-blob
2.rn-fetch-blob 本身有循环依赖问题，不过不影响使用
3.真正产生问题的是必须设置 callback.onComplete，否则下载成功后不会进行安装

**Comment by ma6566966** [comment]
> onComplete
onComplete在那里设置啊

**Comment by ma6566966** [comment]
> 总结一下使用react-native-app-upgrade遇到的几个问题
> 1.在 react-native:0.64.0 版本中，rn-fetch-blob 不会自动连接，需要手动连接或安装 rn-fetch-blob
> 2.rn-fetch-blob 本身有循环依赖问题，不过不影响使用
> 3.真正产生问题的是必须设置 callback.onComplete，否则下载成功后不会进行安装

onComplete在哪里设置啊
