### ISSUE TITLE
Android是放在哪个目录下？文档说是放在main目录下  Issues说放在src下  我两个都试了还是不行啊- -

### ISSUE THREAD

**Issue by niices** [songxiaoliang/react-native-app-upgrade#12]
Android是放在哪个目录下？文档说是放在main目录下  Issues说放在src下  我两个都试了还是不行啊- -

**Comment by songxiaoliang** [comment]
@niices android 是放在src目录下的，放进去后修改对应的包名即可。

**Comment by niices** [comment]
![image](https://user-images.githubusercontent.com/8327775/36664158-c8bc3de2-1b1e-11e8-920b-f9909a65b1bd.png)
![image](https://user-images.githubusercontent.com/8327775/36664175-d4ce5dea-1b1e-11e8-852a-2cdb8d2f4235.png)
我放进去之后是这样引用的
```java
import com.cloudbusiness.upgrade.UpgradePackage;
new UpgradePackage()
```
然后提示我
错误: 程序包com.cloudbusiness.upgrade不存在

**Comment by niices** [comment]
对安卓一窍不通  麻烦了- -

**Comment by songxiaoliang** [comment]
@niices android_upgrade这个文件夹放到yongquan这个目录下，然后com.cloudbusiness改成com.yongquan你这个包名

**Comment by niices** [comment]
嗯嗯  已经搞定了  麻烦了

**Comment by niices** [comment]
这个issue可以关了   感谢感谢
