### ISSUE TITLE
>

### ISSUE THREAD

**Issue by qianshihoushi** [songxiaoliang/react-native-app-upgrade#120]
> 

而且后面发现安卓下载完成后无法自动安装，后面换成其他库了

_Originally posted by @Rain-Pavilion in https://github.com/songxiaoliang/react-native-app-upgrade/issues/115#issuecomment-1211454903_

**Comment by parz1** [comment]
@lijinglun123 方便问一下换成什么库了吗？

**Comment by qianshihoushi** [comment]
> @lijinglun123方便问一下换成什么库了吗？
https://www.npmjs.com/package/rn-update-version 你可以试试用这个

**Comment by parz1** [comment]
@lijinglun123  好的 感谢🙏
