### ISSUE TITLE
使用方法不是很明白

### ISSUE THREAD

**Issue by jiyeon-dino** [songxiaoliang/react-native-app-upgrade#15]
配置已经可以了，使用时
Http.get(Api.api_checkupdate, null, false, (result)=>{  
    if(result.ok) {  
        NativeModules.upgrade.upgrade(this.state.apkUrl);  
    }  
}); 
Http需要import吗？

**Comment by songxiaoliang** [comment]
@jiyeon-dino 这个Http是我封装的一个http请求工具类，你可以按照自己的请求方式写即可。

**Comment by jiyeon-dino** [comment]
好的，这个可以关闭了
