### ISSUE TITLE
请教如何使用

### ISSUE THREAD

**Issue by bluexiaowei** [songxiaoliang/react-native-app-upgrade#18]
亲，我是没有看懂怎么用。
问题1：APP .APK 文件放在服务器，下载地址写在哪呢？
问题2：那个怎么根据下载地址知道下载的版本比当前版本高呢？

**Comment by songxiaoliang** [comment]
@bluexiaowei 这些数据需要在后台去维护的

**Comment by songxiaoliang** [comment]
@bluexiaowei 跟这个库没有关系哈，你仔细看READEME

**Comment by bluexiaowei** [comment]
抱歉，抱歉，刚接触这个 react native 不知道如何操作。 谢谢了。 我以为就像下载那么简单。
