### ISSUE TITLE
群主大大 AndroidManifest.xml 报错了

### ISSUE THREAD

**Issue by showtan001** [songxiaoliang/react-native-app-upgrade#19]
rn 0.44
ugManifest 98% > :app:processDebugManifest
D:\project\taihe_member\android\app\src\main\AndroidManifest.xml:35:13-70 Error:

       Attribute provider#android.support.v4.content.FileProvider@authorities va
lue=(com.xxx.updateFileProvider) from AndroidManifest.xml:35:13-70
  is also present at [taihe:react-native-image-picker:unspecified] AndroidManife
st.xml:14:13-60 value=(com.xxx.provider).
      Suggestion: add 'tools:replace="android:authorities"' to <provider> elemen
t at AndroidManifest.xml:33:9-41:20 to override.
D:\project\taihe_member\android\app\src\main\AndroidManifest.xml:40:17-61 Error:

       Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@
xml/update_file_provider) from AndroidManifest.xml:40:17-61
   is also present at [taihe:react-native-image-picker:unspecified] AndroidManif
est.xml:19:17-55 value=(@xml/provider_paths).
     Suggestion: add 'tools:replace="android:resource"' to <meta-data> element a
t AndroidManifest.xml:38:13-40:64 to override.

See http://g.co/androidstudio/manifest-merger for more information about the man
ifest merger.

:app:processDebugManifest FAILED

**Comment by songxiaoliang** [comment]
@showtan001 image-picker这个库也用到了fileProvider，导致和本库冲突了。这种情况可以修改下image-picker的源码。具体你在群里提问就行。
