### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by combing520** [songxiaoliang/react-native-app-upgrade#2]
Android 的好像不能用， 
DownloadService.java 文件中的 onHandleIntent不会执行

**Comment by songxiaoliang** [comment]
@combing520 亲测，可以使用，

**Comment by combing520** [comment]
你那边是做了什么特殊处理，我是一个小时之前试的。不能用成？大神

**Comment by songxiaoliang** [comment]
@combing520 onHandleIntent是Serivice的处理方法，你在配置文件中是否配置了DownLoadSerivice?

**Comment by combing520** [comment]
这个没有配置， 大神可以将需要 在 清单文件中配置的 代码也放在 这个库的说明文档中？

**Comment by songxiaoliang** [comment]
@combing520 好的，稍等

**Comment by songxiaoliang** [comment]
@combing520 查看readme即可。

**Comment by combing520** [comment]
@songxiaoliang  好的 ，谢谢大神， 大神的库在 Android 7.0 或者更高版本能使用？就是下载后 自动安装？因为现在Android 7.0的机器也越来越多了

**Comment by songxiaoliang** [comment]
@combing520 可以的~你可以尝试一下。

**Comment by combing520** [comment]
@songxiaoliang  嗯，真的是谢谢了，谢谢大神的指导。

**Comment by songxiaoliang** [comment]
@combing520 不客气的，没有问题的话，我先issue关闭啦~

**Comment by combing520** [comment]
@songxiaoliang  好的 ，谢谢
