### ISSUE TITLE
iOS 报错

### ISSUE THREAD

**Issue by Yibay** [songxiaoliang/react-native-app-upgrade#20]
![image](https://user-images.githubusercontent.com/18311200/37949089-b660545e-31c5-11e8-8477-9fe30541bbe6.png)
NativeModules.upgrade 为 undefined

**Comment by Yibay** [comment]
不过 参考upgrade.m 思路，用React Native直接项目里实现也不麻烦。

**Comment by songxiaoliang** [comment]
@Yibay 这个错误不是库的问题哈~
