### ISSUE TITLE
react-native-app-upgrade和react-native-image-crop-picker都用到了fileProvider，导致冲突报错

### ISSUE THREAD

**Issue by MrLinWeiFeng** [songxiaoliang/react-native-app-upgrade#27]
G:\project\sucaiapp_3\android\app\src\main\AndroidManifest.xml:60:13-70 Error:
 Attribute provider#android.support.v4.content.FileProvider@authorities value=(c
om.dadichuangke.updateFileProvider) from AndroidManifest.xml:60:13-70
   is also present at [sucaiapp:react-native-image-crop-picker:unspecified] Andr
oidManifest.xml:15:13-60 value=(com.dadichuangke.provider).
       Suggestion: add 'tools:replace="android:authorities"' to <provider> eleme
nt at AndroidManifest.xml:58:9-66:20 to override.
G:\project\sucaiapp_3\android\app\src\main\AndroidManifest.xml:65:17-61 Error:
 Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/up
date_file_provider) from AndroidManifest.xml:65:17-61
   is also present at [sucaiapp:react-native-image-crop-picker:unspecified] Andr
oidManifest.xml:20:17-55 value=(@xml/provider_paths).
     Suggestion: add 'tools:replace="android:resource"' to <meta-data> element a
t AndroidManifest.xml:63:13-65:64 to override.
> Building 97% > :app:processDebugManifest
See http://g.co/androidstudio/manifest-merger for more information about the man
ifest merger.

:app:processDebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED
请问这该怎么解决，才不影响两个插件的正常使用？

**Comment by songxiaoliang** [comment]
@MrLinWeiFeng 需要修改下image-crop-picker的源码，使用同一个fileprovider就可以了。

**Comment by MrLinWeiFeng** [comment]
@songxiaoliang 能说一下具体要修改那吗？

**Comment by MrLinWeiFeng** [comment]
看到修改方法了，谢谢群主大大

**Comment by lyf1923811803** [comment]
@MrLinWeiFeng 你好！我也遇到这个问题了，请问你是如何解决的呢，谢谢！

**Comment by songxiaoliang** [comment]
@lyf1923811803 具体看下READEME文档。
