### ISSUE TITLE
import com.cloudbusiness.R;

### ISSUE THREAD

**Issue by chenzhenquan** [songxiaoliang/react-native-app-upgrade#29]
我看你的包里面也没有这个类？import com.cloudbusiness.R;
我这边允许时候报了这个错误？请问是什么原因？
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
E:\development\WWW\app.4399.com\app\android\app\src\main\java\com\sy4399\h5\android_upgrade\DownloadService.java:14: ▒▒▒▒: ▒▒▒▒▒com.cloudbusiness▒▒▒▒▒▒
import com.cloudbusiness.R;
                        ^
E:\development\WWW\app.4399.com\app\android\app\src\main\java\com\sy4399\h5\android_upgrade\DownloadService.java:114: ▒▒▒▒: ▒▒▒▒▒R▒▒▒▒▒▒
        mBuilder.setContentText(this.getString(R.string.android_auto_update_download_progress, progress)).setProgress(100, progress, false);
                                                ^
E:\development\WWW\app.4399.com\app\android\app\src\main\java\com\sy4399\h5\android_upgrade\UpgradePackage.java:26: ▒▒▒▒: ▒▒▒▒▒▒▒Ḳ▒ǻ▒ʵ▒ֳ▒▒▒▒͵ķ▒▒▒
    @Override
    ^
ע: ĳЩ▒▒▒▒▒ļ▒ʹ▒û򸲸▒▒▒▒ѹ▒ʱ▒▒ API▒▒
ע: ▒й▒▒▒ϸ▒▒Ϣ, ▒▒ʹ▒▒ -Xlint:deprecation ▒▒▒±▒▒롣
3 ▒▒▒▒▒▒
:app:compileDebugJavaWithJavac FAILED

**Comment by 1uokun** [comment]
+1 @chenzhenquan 请问你怎么解决的呢

**Comment by songxiaoliang** [comment]
@1uokun @chenzhenquan com.cloudbusiness.R将这个修改成自己的包名即可。
