### ISSUE TITLE
版本下载的是时候没有提示

### ISSUE THREAD

**Issue by combing520** [songxiaoliang/react-native-app-upgrade#3]
@songxiaoliang  大神， 刚刚我忘记问了一个问题，就是用您这个库的时候，怎样能够弹出通知栏的消息？ 
现在能够直接用了，但是进行更新的时候 好像是在后台进行了，【没有任何的提示】，我们在通知栏上面也没有看到相关的下载通知，然后下载完成之后就突然弹出一个安装的框， 感觉可以 不是很友好， 可以告诉我们怎样 在下载更新的时候将通知栏消息打开？ 然后下载完成后自动关闭通知栏的消息？

**Comment by songxiaoliang** [comment]
@combing520 当下载时是有通知栏显示的，你可以查看下手机是否关闭了通知提示。

**Comment by combing520** [comment]
@songxiaoliang ，嗯，谢谢，不好意思打搅大神，大神有QQ群或者什么之类的联系方式？ 不然有情况我还需要开 issues. 还要麻烦大神重新关闭，我在试试 7.0 的机器。谢谢

**Comment by songxiaoliang** [comment]
@combing520 563609104 QQ~

**Comment by combing520** [comment]
好的 ，谢谢 ，谢谢。我添加一下，谢谢

**Comment by csyaonie** [comment]
老哥 我也不显示 怎么办啊
