### ISSUE TITLE
请教关于安卓apk的地址问题

### ISSUE THREAD

**Issue by 369663841** [songxiaoliang/react-native-app-upgrade#32]
您好！多谢分享。问题如下：

如果Apk的版本信息和下载地址是类似下面访问后台获取的话：

Http.get(Api.api_checkupdate, null, false, (result)=>{  
    if(result.ok) {  
        // 下载最新Apk  
        NativeModules.upgrade.upgrade(this.state.apkUrl);  
    }  
});  

那么下面的配置信息（比如UPDATE_URL）似乎没用上？
class Constants {

    // json {"url":"http://192.168.205.33:8080/Hello/app_v3.0.1_Other_20150116.apk","versionCode":2,"updateMessage":"版本更新信息"}

    static final String APK_DOWNLOAD_URL = "url";
    static final String APK_UPDATE_CONTENT = "updateMessage";
    static final String APK_VERSION_CODE = "versionCode";

    static final int TYPE_NOTIFICATION = 2;

    static final int TYPE_DIALOG = 1;

    static final String TAG = "UpdateChecker";

    static final String UPDATE_URL = "https://raw.githubusercontent.com/feicien/android-auto-update/develop/extras/update.json";
}

谢谢！

**Comment by songxiaoliang** [comment]
@369663841 
Http.get(Api.api_checkupdate, null, false, (result)=>{
if(result.ok) {
// 下载最新Apk
NativeModules.upgrade.upgrade(this.state.apkUrl);
}
});
上面这段代码表示获取是否需要更新，而具体的下载信息是需要咋Constants上去配置的。

**Comment by 369663841** [comment]
@songxiaoliang 谢谢！
