### ISSUE TITLE
请问一下，后台应该在哪里返回版本号？而前台又该在哪里对比版本号呢？

### ISSUE THREAD

**Issue by 90636174** [songxiaoliang/react-native-app-upgrade#37]
Http.get(Api.api_checkupdate, null, false, (result)=>{  
    if(result.ok) {  
        // 下载最新Apk  
        NativeModules.upgrade.upgrade(this.state.apkUrl);  
    }  
});
result  是怎么得到的？

**Comment by Hahahaooovvv** [comment]
Http.get 意思是通过一个GET请求服务器 react是服务器给你返回来的数据 其中肯定包含一个版本号信息 和一个下载地址  还可能包含版本升级信息什么的 你通过判断哪个版本信息 来和本地的版本判断是否一致 不一致就直接更新了呀
