### ISSUE TITLE
兼容Android8.0

### ISSUE THREAD

**Issue by binbinla** [songxiaoliang/react-native-app-upgrade#41]
安装升级还有通知栏没有做兼容Android8.0系统的操作

**Comment by songxiaoliang** [comment]
@binbinla 是的，这块有时间完善一下。

**Comment by chyonglong** [comment]
@songxiaoliang 8.0可以兼容了吗？

**Comment by xiaods** [comment]
兼容怎么做一下

**Comment by songxiaoliang** [comment]
@xiaods @chyonglong @binbinla 已经适配Android 8.0

**Comment by songxiaoliang** [comment]
@xiaods @chyonglong @binbinla 已经适配Android 8.0
