### ISSUE TITLE
建议作者更正Readme

### ISSUE THREAD

**Issue by mifeng9999** [songxiaoliang/react-native-app-upgrade#42]
1.所有的类的package都需要修改为自己的路径地址。
2.DownloadService类中import com.*.*.R修改为自己的app地址名称，124行的Build.VERSION_CODES.N修改为.M对象。
3.需要使用者阅读Constants类，才能明白更新请求原理。
4.MainApplication中import 项目工程包名.UpgradePackage中的项目工程包名其实不对，应该是import com.*.*.android_upgrade.UpgradePackage。
5.compileSdkVersion 26 buildToolsVersion '26' 这两个不能随便修改，会影响其他的库。应该做个说明。
6.最后建议作者应该提交一个案例（胜过N个说明），最后希望作者以后最好以图文的方式做说明。
关于自己的开发：
最终可以运行并发布到真机，But提示解析包错误，无法更新APP。决定放弃此方式。谨以此提示其他使用者和作者。

**Comment by songxiaoliang** [comment]
@mifeng9999 感谢建议，近期会更新

**Comment by zjgnlzq** [comment]
坑爹的项目，一个废品发上来浪费大家时间
