### ISSUE TITLE
下载进度不一致

### ISSUE THREAD

**Issue by Fengtianhe** [songxiaoliang/react-native-app-upgrade#45]
![image](https://user-images.githubusercontent.com/15321902/43573605-b4d013d6-9674-11e8-8045-0deb84a7d538.png)
都下载完了但是下载进度还在15+，
是哪里需要改配置么

**Comment by wl05** [comment]
+1

**Comment by wangyihang875** [comment]
程序里返回的和通知栏的也不一致

**Comment by GuoJiKaiHehe** [comment]
+1

**Comment by dzxxdzy** [comment]
+1

**Comment by 78720705** [comment]
+1
