### ISSUE TITLE
UpgradePackage.java:26: 错误: 方法不会覆盖或实现超类型的方

### ISSUE THREAD

**Issue by zjgnlzq** [songxiaoliang/react-native-app-upgrade#46]
UpgradePackage.java:26: 错误: 方法不会覆盖或实现超类型的方

**Comment by zjgnlzq** [comment]
@songxiaoliang

**Comment by songxiaoliang** [comment]
@zjgnlzq 低版本还是需要的，目前在高版本上可以剔除。在READEME已说明。

**Comment by wangyihang875** [comment]
> @zjgnlzq 低版本还是需要的，目前在高版本上可以剔除。在READEME已说明。

没看到READEME上有相关说明，在哪一段？
