### ISSUE TITLE
当使用剪裁插件react-native-syan-image-picker怎么办？

### ISSUE THREAD

**Issue by zSergeant** [songxiaoliang/react-native-app-upgrade#47]
/Users/*******/android/app/src/main/AndroidManifest.xml:44:17-74 Error:
	Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.zishahui.debug.updateFileProvider) from AndroidManifest.xml:44:17-74
	is also present at [:react-native-syan-image-picker] AndroidManifest.xml:18:13-60 value=(com.zishahui.debug.provider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:42:9-50:20 to override.
/Users/*******/android/app/src/main/AndroidManifest.xml:49:21-65 Error:
	Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/update_file_provider) from AndroidManifest.xml:49:21-65
	is also present at [:react-native-syan-image-picker] AndroidManifest.xml:23:17-51 value=(@xml/file_paths).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml:47:13-49:68 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by songxiaoliang** [comment]
@zSergeant 使用同一个filerprovider即可。
