### ISSUE TITLE
DownloadService.java文件报错

### ISSUE THREAD

**Issue by lhh-sofy** [songxiaoliang/react-native-app-upgrade#49]
该文件引入了import com.cloudbusiness.R;
但是代码中没有此文件。错误如图：
<img width="811" alt="09d51975-0ba2-4808-a937-a578e1984530" src="https://user-images.githubusercontent.com/13582183/47694140-6922cb00-dc37-11e8-9379-08e9dd6ab84d.png">

**Comment by songxiaoliang** [comment]
@lhh-sofy   R.string.android_auto_update_download_progress，检查在res/values/string.xml中是否配置了。

**Comment by lhh-sofy** [comment]
好的，多谢，已解决该问题
