### ISSUE TITLE
大神~安卓下的UpgradePackage.java为什么会报‘方法不会覆盖或实现超类型的方法‘的错啊

### ISSUE THREAD

**Issue by qiansitong** [songxiaoliang/react-native-app-upgrade#5]

**Comment by songxiaoliang** [comment]
@qiansitong 这个跟RN 版本有关系，如果RN >0.46，要将package中的createJSModule删除即可。

**Comment by wangyihang875** [comment]
> @qiansitong 这个跟RN 版本有关系，如果RN >=0.46，要将package中的createJSModule删除即可。

我是0.46.4，发现还是要保留createJSModules

**Comment by songxiaoliang** [comment]
@wangyihang875 低版本是要保留。
