### ISSUE TITLE
下载https时候，报错

### ISSUE THREAD

**Issue by lhh-sofy** [songxiaoliang/react-native-app-upgrade#51]
你好，当我的apk的地址是放在七牛云上，下载地址是https的时候，下载失败
错误日志为：
E/DownloadService: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Wed Sep 12 19:59:59 EDT 2018 (compared to Tue Oct 30 23:24:02 EDT 2018)

**Comment by songxiaoliang** [comment]
@lhh-sofy https需要配置校验证书。

**Comment by lhh-sofy** [comment]
哦，这样啊，那有木有通用的解决方案啊.在网上有搜到过，但是不懂安卓代码.可以抽空看一下么，非常感谢🙏
