### ISSUE TITLE
Error:(111, 9) 错误: 找不到符号 符号:   变量 UpgradeModule 位置: 类 DownloadService

### ISSUE THREAD

**Issue by huangye2018** [songxiaoliang/react-native-app-upgrade#53]
react-native run-android和android  studio运行安卓代码也是这样。请问怎么解决？

**Comment by wangyihang875** [comment]
same issues

**Comment by wangyihang875** [comment]
一样的问题，有解决方案了吗？

**Comment by huangye2018** [comment]
搞定了的，你用IDE工具打开可以看见是路径错了




------------------ 原始邮件 ------------------
发件人: "wangyihang"<notifications@github.com>;
发送时间: 2018年12月17日(星期一) 上午10:47
收件人: "songxiaoliang/react-native-app-upgrade"<react-native-app-upgrade@noreply.github.com>;
抄送: "杨胜江"<1195839393@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [songxiaoliang/react-native-app-upgrade] Error:(111, 9) 错误: 找不到符号 符号:   变量 UpgradeModule 位置: 类 DownloadService (#53)




一样的问题，有解决方案了吗？
