### ISSUE TITLE
android SDK api 28

### ISSUE THREAD

**Issue by hypertextPreprocessor** [songxiaoliang/react-native-app-upgrade#70]
import android.support.v4.app.NotificationCompat.Builder;
import android.support.v4.content.FileProvider;
这两个api 在sdk 28版本没法用如何解决？

**Comment by premillos** [comment]
我也有同样的问题

**Comment by Ben002** [comment]
// import android.support.v4.app.NotificationCompat.Builder;
// import android.support.v4.content.FileProvider;
用下面的代替一下试试：
import androidx.core.app.NotificationCompat.Builder;
import androidx.core.content.FileProvider;

**Comment by tr2v** [comment]
> // import android.support.v4.app.NotificationCompat.Builder;
> // import android.support.v4.content.FileProvider;
> 用下面的代替一下试试：
> import androidx.core.app.NotificationCompat.Builder;
> import androidx.core.content.FileProvider;

可以解决

**Comment by songxiaoliang** [comment]
已更新代码.该issue已关闭.
