### ISSUE TITLE
在AndroidMainfest.xml中增加provider后程序打开就闪退

### ISSUE THREAD

**Issue by PHPzhong** [songxiaoliang/react-native-app-upgrade#74]
<provider
                android:name=".android_upgrade.FileProviderAdapter"
                android:authorities="${applicationId}.updateFileProvider"
                android:exported="false"
                android:grantUriPermissions="true">
            <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/update_file_provider" />
        </provider>

**Comment by fynmm** [comment]
一样啊，怎么解决啊？
