### ISSUE TITLE
如何判断是否正在下载apk

### ISSUE THREAD

**Issue by jun58** [songxiaoliang/react-native-app-upgrade#76]
我按照步骤，不同的是，在下载的文件中，我的androidx编译报错，所以我用android.support.v4代替了androidx.core，如下图：
![image](https://user-images.githubusercontent.com/20509429/65756262-4babf900-e147-11e9-91d8-3156d641d083.png)
做了这样的替换之后，编译是不报错了，可以运行起来，但是
![image](https://user-images.githubusercontent.com/20509429/65756339-80b84b80-e147-11e9-8e2e-c4000cf9cf07.png)
这里做了监听，并没有东西显示，我也没有任何的依据去确定是否apk在下载。现在我想知道的是这个项目是否本身是没有问题的，是不是我之前用android.support.v4代替了androidx.core的原因

**Comment by songxiaoliang** [comment]
@jun58 androidx只是为了适配android sdk 28以上的版本.如果没有任何响应,建议检查手机是否关闭的下载权限,以及apk的下载链接是否可以正常使用
