### ISSUE TITLE
错误: 程序包androidx.core.app.NotificationCompat不存在

### ISSUE THREAD

**Issue by error-code** [songxiaoliang/react-native-app-upgrade#77]
**求教这个什么问题**

`E:\ReactNative\ladder\android\app\src\main\java\com\ladder\android_upgrade\DownloadService.java:11: 错误: 程序包androidx.core.app.NotificationCompat不存在
import androidx.core.app.NotificationCompat.Builder;
                                           ^
E:\ReactNative\ladder\android\app\src\main\java\com\ladder\android_upgrade\DownloadService.java:12: 错误: 程序包androidx.core.content不存在
import androidx.core.content.FileProvider;
                            ^
E:\ReactNative\ladder\android\app\src\main\java\com\ladder\android_upgrade\DownloadService.java:30: 错误: 找不到符号
    private Builder mBuilder;
            ^
  符号:   类 Builder
  位置: 类 DownloadService
E:\ReactNative\ladder\android\app\src\main\java\com\ladder\android_upgrade\FileProviderAdapter.java:2: 错误: 程序包androidx.core.content不存在
import androidx.core.content.FileProvider;
                            ^
E:\ReactNative\ladder\android\app\src\main\java\com\ladder\android_upgrade\FileProviderAdapter.java:4: 错误: 找不到符号
public class FileProviderAdapter extends FileProvider {
                                         ^
  符号: 类 FileProvider
E:\ReactNative\ladder\android\app\src\main\java\com\ladder\android_upgrade\DownloadService.java:42: 错误: 找不到符号
            mBuilder = new Builder(this, "downLoadChannelId");
                           ^
  符号:   类 Builder
  位置: 类 DownloadService
E:\ReactNative\ladder\android\app\src\main\java\com\ladder\android_upgrade\DownloadService.java:46: 错误: 找不到符号
            mBuilder = new Builder(this);
                           ^
  符号:   类 Builder
  位置: 类 DownloadService
E:\ReactNative\ladder\android\app\src\main\java\com\ladder\android_upgrade\DownloadService.java:134: 错误: 找不到符号
            Uri apkUri = FileProvider.getUriForFile(this, authority, apkFile);
                         ^
  符号:   变量 FileProvider
  位置: 类 DownloadService`

**Comment by webxiaohe** [comment]
androidx配置有问题，我的解决办法是改为android
修改androidx.core.app.NotificationCompat.Builder; 为android.support.v4.app.NotificationCompat.Builder
修改androidx.core.content.FileProvider;  为android.support.v4.content.FileProvider

**Comment by songxiaoliang** [comment]
@error-code @webxiaohe 可以升级sdk 28, 适配androidx.

**Comment by webxiaohe** [comment]
@songxiaoliang 
这是我的项目的sdk, 但是使用androidx.core.app.NotificationCompat还是会报错
ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
}

**Comment by songxiaoliang** [comment]
@重新rebuild了吗?

**Comment by webxiaohe** [comment]
@songxiaoliang 
我运行 cd android && ./gradlew clean  
然后重新react-native run-android就报错了：
/java/com/android_upgrade/DownloadService.java:12: 错误: 程序包androidx.core.content不存在

**Comment by songxiaoliang** [comment]
@webxiaohe 我估计是最新包没有下载下来

**Comment by webxiaohe** [comment]
@songxiaoliang  rn从0.6开始支持androidx, 我刚刚重新创建一个0.6的项目，发现成功了

**Comment by ShaoGongBra** [comment]
0.59 没办法升级的项目怎么兼容呢

**Comment by songxiaoliang** [comment]
@ShaoGongBra 
可以参考上面 @webxiaohe 的解决方案

**Comment by ShaoGongBra** [comment]
修改androidx.core.content.FileProvider; 为android.support.v4.content.FileProvider

参照这个改了，之后会包找不到FileProvider.getUriForFile 不存在
