### ISSUE TITLE
为什么获取不到versionName和versionCode

### ISSUE THREAD

**Issue by error-code** [songxiaoliang/react-native-app-upgrade#83]
rn 5.9\6.0 都获取不到呢
结果都是：undefined

**Comment by tanhaoAli** [comment]
监听进度结果也是undefined    RN0.6版本

**Comment by tanhaoAli** [comment]
> rn 5.9\6.0 都获取不到呢
> 结果都是：undefined

可以通过NativeModules.upgrade进行获取

**Comment by error-code** [comment]
> > rn 5.9\6.0 都获取不到呢
> > 结果都是：undefined
> 
> 可以通过NativeModules.upgrade进行获取

谢谢，我试下
