### ISSUE TITLE
DownloadService.java:44: 错误: 无法将类 Builder中的构造器 Builder应用到给定类型;             mBuilder = new Builder(this,"downLoadChannelId");                        ^   需要: Context   找到: DownloadService,String   原因: 实际参数列表和形式参数列表长度不同

### ISSUE THREAD

**Issue by k1195453766** [songxiaoliang/react-native-app-upgrade#84]
DownloadService.java:44: 错误: 无法将类 Builder中的构造器 Builder应用到给定类型;
            mBuilder = new Builder(this,"downLoadChannelId");
                       ^
  需要: Context
  找到: DownloadService,String
  原因: 实际参数列表和形式参数列表长度不同

请问楼主这个问题怎么解决？

**Comment by songxiaoliang** [comment]
@k1195453766 import android.support.v4.app.NotificationCompat.Builder; 目前使用的是v4包下面的, 你看下你的sdk版本是多少?

**Comment by k1195453766** [comment]
rn:0.50.1(有点老，早年的项目，一直没敢升级)
targetSdkVersion 27

**Comment by songxiaoliang** [comment]
@k1195453766 那应该是没问题的呀

**Comment by k1195453766** [comment]
是的，之前没有npm的时候是可以的，我和之前的用的代码也对比过了，这部分是一样的，都是用的v4包下边的，但是用npm导入后就报错了；现在是不是同样可以直接把文件夹copy下来放到项目呢？

**Comment by songxiaoliang** [comment]
@k1195453766 可以的, 先copy到项目工程吧

**Comment by k1195453766** [comment]
好的，谢谢，我先试试
