### ISSUE TITLE
FileProvider， List没有import

### ISSUE THREAD

**Issue by lf7817** [songxiaoliang/react-native-app-upgrade#87]
``DownloadService``里的**FileProvider**，还有``ApkDonLoadSuccessReceiver``里的**List**没有引入就使用了，导致报错，希望大佬可以更新一下

**Comment by songxiaoliang** [comment]
@lf7817 谢谢， 已更新

**Comment by lf7817** [comment]
啥时候能更新npm包啊大佬，我现在只能自己fork发布了

**Comment by songxiaoliang** [comment]
@lf7817 npm 已更新了哈， 最新版本 1.2.0
