### ISSUE TITLE
react-native 0.57.8

### ISSUE THREAD

**Issue by Lloyd1229** [songxiaoliang/react-native-app-upgrade#89]
> Task :rn-app-upgrade:compileDebugJavaWithJavac FAILED
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/ApkDonLoadSuccessReceiver.java:9: 错误: 程序包androidx.core.content不存在
import androidx.core.content.FileProvider;
                            ^
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/FileProviderAdapter.java:2: 错误: 程序包androidx.core.content不存在
import androidx.core.content.FileProvider;
                            ^
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/FileProviderAdapter.java:4: 错误: 找不到符号
public class FileProviderAdapter extends FileProvider {
                                         ^
  符号: 类 FileProvider
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/DownloadService.java:12: 错误: 程序包androidx.core.app.NotificationCompat不存在
import androidx.core.app.NotificationCompat.Builder;
                                           ^
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/DownloadService.java:13: 错误: 程序包androidx.core.content不存在
import androidx.core.content.FileProvider;
                            ^
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/DownloadService.java:33: 错误: 找不到符号
    private Builder mBuilder;
            ^
  符号:   类 Builder
  位置: 类 DownloadService
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/DownloadService.java:34: 错误: 找不到符号
    private Builder mDownLoadSuccessBuilder;
            ^
  符号:   类 Builder
  位置: 类 DownloadService
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/ApkDonLoadSuccessReceiver.java:51: 错误: 找不到符号
            Uri apkUri = FileProvider.getUriForFile(context, authority, apkFile);
                         ^
  符号:   变量 FileProvider
  位置: 类 ApkDonLoadSuccessReceiver
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/DownloadService.java:46: 错误: 找不到符号
            mBuilder = new Builder(this, "downLoadChannelId");
                           ^
  符号:   类 Builder
  位置: 类 DownloadService
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/DownloadService.java:50: 错误: 找不到符号
            mBuilder = new Builder(this);
                           ^
  符号:   类 Builder
  位置: 类 DownloadService
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/DownloadService.java:139: 错误: 找不到符号
            Uri apkUri = FileProvider.getUriForFile(this, authority, apkFile);
                         ^
  符号:   变量 FileProvider
  位置: 类 DownloadService
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/DownloadService.java:196: 错误: 找不到符号
            mDownLoadSuccessBuilder = new Builder(this, "downLoadSuccessChannelId");
                                          ^
  符号:   类 Builder
  位置: 类 DownloadService
/Users/lloyd/Documents/react-native-project/company/sandroid/shop/node_modules/rn-app-upgrade/android/src/main/java/com/songlcy/rnupgrade/DownloadService.java:200: 错误: 找不到符号
            mDownLoadSuccessBuilder = new Builder(this);
                                          ^
  符号:   类 Builder
  位置: 类 DownloadService
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
13 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rn-app-upgrade:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by songxiaoliang** [comment]
@Lloyd1229 针对不支持androidx的RN版本，请查看READEME.md中详细的注意事项
