### ISSUE TITLE
updateFileProvider

### ISSUE THREAD

**Issue by Sudors** [songxiaoliang/react-native-app-upgrade#9]
你好 mainfest 里的 ${applicationId}.updateFileProvider 是不是没有放出来。sync的时候 编译不过

**Comment by songxiaoliang** [comment]
@Sudors 什么叫没放出来呢？没太明白。这块是没问题的，你看下是否配置了xml的provider

**Comment by Sudors** [comment]
解决了，FileProvider 冲突 需要自定义一个！

**Comment by songxiaoliang** [comment]
@Sudors 好的，该issue先关闭了，有任何问题都可以再直接提
