### ISSUE TITLE
请问如何获取版本号？我一直没找到！感谢大神

### ISSUE THREAD

**Issue by DestinyJun** [songxiaoliang/react-native-app-upgrade#97]

**Comment by Qujh97** [comment]
我是直接跑不起来。可以用react-native-device-info获取版本号

**Comment by DestinyJun** [comment]
> 我是直接跑不起来。可以用react-native-device-info获取版本号

我的已经踩坑好了，是因为其npm上的包里面的代码不全，没有把获取版本号的代码加进去，自己手动加进去就行，没有跑起来你注意去看下的Android sdk有没有下载这个插件对应的sdk版本以及build-tools的版本，因为这个差价比较老，如果你的sdk只下载了最新版的话，会导致编译不通过，如果有什么需要交流的欢迎+qq 429771890

**Comment by Qujh97** [comment]
> > 我是直接跑不起来。可以用react-native-device-info获取版本号
> 
> 我的已经踩坑好了，是因为其npm上的包里面的代码不全，没有把获取版本号的代码加进去，自己手动加进去就行，没有跑起来你注意去看下的Android sdk有没有下载这个插件对应的sdk版本以及build-tools的版本，因为这个差价比较老，如果你的sdk只下载了最新版的话，会导致编译不通过，如果有什么需要交流的欢迎+qq 429771890

感谢🙏，解决了

**Comment by DestinyJun** [comment]
> > > 我是直接跑不起来。可以用react-native-device-info获取版本号
> > 
> > 
> > 我的已经踩坑好了，是因为其npm上的包里面的代码不全，没有把获取版本号的代码加进去，自己手动加进去就行，没有跑起来你注意去看下的Android sdk有没有下载这个插件对应的sdk版本以及build-tools的版本，因为这个差价比较老，如果你的sdk只下载了最新版的话，会导致编译不通过，如果有什么需要交流的欢迎+qq 429771890
> 
> 感谢🙏，解决了

不客气

**Comment by wulaizi** [comment]
在底部callback改成    NSDictionary *callbackData=@{
      @"status":@"YES", @"appInfo":dic!=nil?dic:@""
    };
    callback(@[callbackData]);  这样  即可得到app全部数据

**Comment by DestinyJun** [comment]
> 在底部callback改成 NSDictionary *callbackData=@{
> @"status":@"YES", @"appInfo":dic!=nil?dic:@""
> };
> callback(@[callbackData]); 这样 即可得到app全部数据

好的嘞，感谢大神
